# Read the Docs configuration file

# Required
version: 2

# Optionally build your docs in additional formats such as PDF
formats:
 - pdf
 - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
