[package]
name = "flipper"
author = "john doe"
import_paths = []
import_maps = []
files = ["flipper.sol"]
contracts = ["flipper"]

[target]
name = "solana"

[debug-features]
prints = true
log-runtime-errors = true
llvm-IR-debug-info = false

[optimizations]
dead_storage = true
constant_folding = true
strength_reduce = true
vector_to_slice = true
common_subexpression_elimination = true
llvm-IR_optimization_level = "default"

[compiler-output]
#verbose = false
#emit = "llvm-ir"
#output_directory = 
#metadata_output_directory= 
