// SPDX-License-Identifier: Apache-2.0

use crate::{build_solidity, SorobanEnv};
use soroban_sdk::{Address, Bytes, BytesN, FromVal, IntoVal};

// Every expected digest fixture in this file was generated by an INDEPENDENT
// implementation, never by the Soroban host itself, making each assert a
// genuine cross-check.
//
// For SHA-256, the `sha256sum` CLI was used.
// For Keccak-256, the `tiny-keccak` crate was used. (Note: Ethereum-style
// Keccak-256, NOT NIST SHA3-256 — they differ in the padding start byte.)

const SHA256_SRC: &str = r#"contract Hasher {
    function sha(bytes memory input) public pure returns (bytes32) {
        return sha256(input);
    }
}"#;

const KECCAK_SRC: &str = r#"contract Hasher {
    function kec(bytes memory input) public pure returns (bytes32) {
        return keccak256(input);
    }
}"#;

fn deploy(src: &str) -> (SorobanEnv, Address) {
    let env = build_solidity(src, |_| {});
    let addr = env.contracts.last().unwrap().clone();
    (env, addr)
}

fn invoke_hash(env: &SorobanEnv, addr: &Address, fn_name: &str, input: &[u8]) -> [u8; 32] {
    let payload = Bytes::from_slice(&env.env, input);
    let raw = env.invoke_contract(addr, fn_name, vec![payload.into_val(&env.env)]);
    BytesN::<32>::from_val(&env.env, &raw).to_array()
}

// SHA256

#[test]
fn sha256_empty_input() {
    let (env, addr) = deploy(SHA256_SRC);

    let expected: [u8; 32] = [
        0xe3, 0xb0, 0xc4, 0x42, 0x98, 0xfc, 0x1c, 0x14, 0x9a, 0xfb, 0xf4, 0xc8, 0x99, 0x6f, 0xb9,
        0x24, 0x27, 0xae, 0x41, 0xe4, 0x64, 0x9b, 0x93, 0x4c, 0xa4, 0x95, 0x99, 0x1b, 0x78, 0x52,
        0xb8, 0x55,
    ];

    assert_eq!(invoke_hash(&env, &addr, "sha", b""), expected);
}

#[test]
fn sha256_is_deterministic_and_distinguishing() {
    let (env, addr) = deploy(SHA256_SRC);

    let a = invoke_hash(&env, &addr, "sha", b"hello world");
    let b = invoke_hash(&env, &addr, "sha", b"hello world");
    let c = invoke_hash(&env, &addr, "sha", b"hello world!");

    assert_eq!(a, b, "sha256 must be deterministic for identical input");
    assert_ne!(a, c, "sha256 must differ for distinct inputs");
}

#[test]
fn sha256_handles_large_input() {
    let (env, addr) = deploy(SHA256_SRC);

    let payload = vec![0xAAu8; 1024];
    let digest = invoke_hash(&env, &addr, "sha", &payload);

    let digest2 = invoke_hash(&env, &addr, "sha", &payload);
    assert_eq!(digest, digest2);
}

// Keccak256

#[test]
fn keccak256_empty_input() {
    let (env, addr) = deploy(KECCAK_SRC);

    let expected: [u8; 32] = [
        0xc5, 0xd2, 0x46, 0x01, 0x86, 0xf7, 0x23, 0x3c, 0x92, 0x7e, 0x7d, 0xb2, 0xdc, 0xc7, 0x03,
        0xc0, 0xe5, 0x00, 0xb6, 0x53, 0xca, 0x82, 0x27, 0x3b, 0x7b, 0xfa, 0xd8, 0x04, 0x5d, 0x85,
        0xa4, 0x70,
    ];

    assert_eq!(invoke_hash(&env, &addr, "kec", b""), expected);
}

#[test]
fn keccak256_is_deterministic_and_distinguishing() {
    let (env, addr) = deploy(KECCAK_SRC);

    let a = invoke_hash(&env, &addr, "kec", b"hello world");
    let b = invoke_hash(&env, &addr, "kec", b"hello world");
    let c = invoke_hash(&env, &addr, "kec", b"hello world!");

    assert_eq!(a, b, "keccak256 must be deterministic for identical input");
    assert_ne!(a, c, "keccak256 must differ for distinct inputs");
}

#[test]
fn keccak256_handles_large_input() {
    let (env, addr) = deploy(KECCAK_SRC);

    let payload = vec![0xAAu8; 1024];
    let digest = invoke_hash(&env, &addr, "kec", &payload);

    let digest2 = invoke_hash(&env, &addr, "kec", &payload);
    assert_eq!(digest, digest2);
}

// Cross-algorithm & padding boundaries

#[test]
fn sha256_and_keccak256_differ_on_same_input() {
    let (s_env, s_addr) = deploy(SHA256_SRC);
    let (k_env, k_addr) = deploy(KECCAK_SRC);

    let s = invoke_hash(&s_env, &s_addr, "sha", b"hello");
    let k = invoke_hash(&k_env, &k_addr, "kec", b"hello");

    assert_ne!(
        s, k,
        "sha256 and keccak256 of the same input must not match"
    );
}

#[test]
fn sha256_at_block_boundary_lengths() {
    // SHA-256 processes input in 64-byte blocks and appends a 9-byte mandatory
    // trailer (1 byte 0x80 + 8-byte big-endian length). Following three lengths
    // cover all padding boundary cases:
    //
    //   L = 55: trailer fits in the same block as the data
    //           (the largest L where everything still hashes in 1 block).
    //   L = 56: only 8 bytes remain in the partial block. The 0x80 fits but the
    //           8-byte length field doesn't, it forces a fresh second block
    //           of [56 zeros] [8-byte length].
    //   L = 64: data fills block 1 exactly; the entire trailer occupies block 2
    //           as [0x80] [55 zeros] [8-byte length].
    let (env, addr) = deploy(SHA256_SRC);

    let payload_55 = vec![b'a'; 55];
    let payload_56 = vec![b'a'; 56];
    let payload_64 = vec![b'a'; 64];

    let h55: [u8; 32] = [
        0x9f, 0x43, 0x90, 0xf8, 0xd3, 0x0c, 0x2d, 0xd9, 0x2e, 0xc9, 0xf0, 0x95, 0xb6, 0x5e, 0x2b,
        0x9a, 0xe9, 0xb0, 0xa9, 0x25, 0xa5, 0x25, 0x8e, 0x24, 0x1c, 0x9f, 0x1e, 0x91, 0x0f, 0x73,
        0x43, 0x18,
    ];
    let h56: [u8; 32] = [
        0xb3, 0x54, 0x39, 0xa4, 0xac, 0x6f, 0x09, 0x48, 0xb6, 0xd6, 0xf9, 0xe3, 0xc6, 0xaf, 0x0f,
        0x5f, 0x59, 0x0c, 0xe2, 0x0f, 0x1b, 0xde, 0x70, 0x90, 0xef, 0x79, 0x70, 0x68, 0x6e, 0xc6,
        0x73, 0x8a,
    ];
    let h64: [u8; 32] = [
        0xff, 0xe0, 0x54, 0xfe, 0x7a, 0xe0, 0xcb, 0x6d, 0xc6, 0x5c, 0x3a, 0xf9, 0xb6, 0x1d, 0x52,
        0x09, 0xf4, 0x39, 0x85, 0x1d, 0xb4, 0x3d, 0x0b, 0xa5, 0x99, 0x73, 0x37, 0xdf, 0x15, 0x46,
        0x68, 0xeb,
    ];

    assert_eq!(invoke_hash(&env, &addr, "sha", &payload_55), h55);
    assert_eq!(invoke_hash(&env, &addr, "sha", &payload_56), h56);
    assert_eq!(invoke_hash(&env, &addr, "sha", &payload_64), h64);
}

#[test]
fn keccak256_at_block_boundary_lengths() {
    // Keccak-256 processes input in 136-byte blocks and uses Ethereum-style multi-rate padding: append
    // 0x01, then zeros, then 0x80 as the final byte of the last block. If
    // only ONE byte of padding space remains, the two markers are OR'd into
    // a single 0x81 byte. Following three lengths cover all padding boundary cases.

    //   L = 134: trailer fits as separate 0x01 + 0x80 bytes in the partial
    //            block (the largest L where padding is two distinct bytes).
    //   L = 135: ONLY 1 byte of pad space left, so the pad byte is the
    //            combined 0x81.
    //   L = 136: data ends exactly on a block boundary; an entire fresh
    //            block of [0x01, 134 zeros, 0x80] gets appended.
    let (env, addr) = deploy(KECCAK_SRC);

    let payload_134 = vec![b'a'; 134];
    let payload_135 = vec![b'a'; 135];
    let payload_136 = vec![b'a'; 136];

    let k134: [u8; 32] = [
        0xe5, 0xde, 0x56, 0x53, 0x99, 0x4e, 0x2f, 0xa6, 0x72, 0x9d, 0x32, 0x9b, 0x65, 0xb5, 0xf3,
        0x32, 0xde, 0xe9, 0x42, 0xa7, 0xea, 0x54, 0x51, 0x5e, 0x17, 0x38, 0x24, 0xc2, 0x32, 0xa4,
        0xff, 0x91,
    ];
    let k135: [u8; 32] = [
        0x34, 0x36, 0x7d, 0xc2, 0x48, 0xbb, 0xd8, 0x32, 0xf4, 0xe3, 0xe6, 0x9d, 0xfa, 0xac, 0x2f,
        0x92, 0x63, 0x8b, 0xd0, 0xbb, 0xd1, 0x8f, 0x29, 0x12, 0xba, 0x4e, 0xf4, 0x54, 0x91, 0x9c,
        0xf4, 0x46,
    ];
    let k136: [u8; 32] = [
        0xa6, 0xc4, 0xd4, 0x03, 0x27, 0x9f, 0xe3, 0xe0, 0xaf, 0x03, 0x72, 0x9c, 0xaa, 0xda, 0x83,
        0x74, 0xb5, 0xca, 0x54, 0xd8, 0x06, 0x53, 0x29, 0xa3, 0xeb, 0xca, 0xeb, 0x4b, 0x60, 0xaa,
        0x38, 0x6e,
    ];

    assert_eq!(invoke_hash(&env, &addr, "kec", &payload_134), k134);
    assert_eq!(invoke_hash(&env, &addr, "kec", &payload_135), k135);
    assert_eq!(invoke_hash(&env, &addr, "kec", &payload_136), k136);
}
