[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor = "z7FbDfQDfucxJz5o8jrGLgvSbdoeSqX5VrxBb5TVjHq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
